server:
  port: 8080

spring:
  datasource:
    username: root
    password: 214923
    url: jdbc:mysql://localhost:3306/logintest?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.test_wxrequest.domain


#showsql
logging:
  level:
    com:
      example:
        mybatisdemo:
          mapper: debug